provise script code-style updates

diff --git a/provise b/provise
--- a/provise
+++ b/provise
@@ -1,9 +1,19 @@
 #!/usr/bin/env bash
 
+set -e
+set -o pipefail
+
+umask 077
+
 # TUI text color helpers
-function echo_ok() { echo -e '\033[1;32m'"$1"'\033[0m'; }
-function echo_err() { echo -e '\033[1;31mERROR: '"$1"'\033[0m'; }
-function echo_warn() { echo -e '\033[1;33m'"$1"'\033[0m'; }
+echo_ok() { echo -e '\033[1;32m'"$1"'\033[0m'; }
+echo_err() { echo -e '\033[1;31mERROR: '"$1"'\033[0m'; }
+echo_warn() { echo -e '\033[1;33m'"$1"'\033[0m'; }
+
+fatal_err() {
+  echo_err "$1"
+  exit 1
+}
 
 # TODO:
 # - use [] instead of verbal 'test' command
@@ -23,11 +33,10 @@ secrets_dir="$script_dir/secrets"
 config_path="$script_dir/secrets/settings.conf"
 
 # Check secrets directory
-test -d "$secrets_dir" || { echo_err "$secrets_dir directory not found" && exit 1; }
+[ -d "$secrets_dir" ] || fatal_err "$secrets_dir directory not found"
 
 # Check and load configuration file
-test -f "$config_path" || \
-  { echo_err "Config file missing at path: $config_path" && exit 1; }
+[ -f "$config_path" ] || fatal_err "Config file missing at path: $config_path"
 
 source "$config_path"
 
@@ -35,61 +44,60 @@ source "$config_path"
 required_variables=(remote_user ssh_connection_string)
 
 for var in "${required_variables[@]}"; do
-  test -n "${!var}" || { echo_err "$var not defined in $config_path" && exit 1; }
+  test -n "${!var}" || fatal_err "$var not defined in $config_path"
 done
 
 # check for all required server configuration files are present
 sshd_config_path="${script_dir}/server_configs/sshd_config"
-test -f "$sshd_config_path" || { echo_err "$sshd_config_path missing" && exit 1; }
+[ -f "$sshd_config_path" ] || fatal_err "$sshd_config_path missing"
 
 dockerd_config_path="${script_dir}/server_configs/docker/daemon.json"
-test -f "$dockerd_config_path" || { echo_err "$dockerd_config_path missing" && exit 1; }
+[ -f "$dockerd_config_path" ] || fatal_err "$dockerd_config_path missing"
 
 # check backup script
 backup_script_path="${script_dir}/backup"
-test -f "$backup_script_path" || { echo_err "$backup_script_path missing" && exit 1; }
+[ -f "$backup_script_path" ] || fatal_err "$backup_script_path missing"
 
 # check local user public key
 local_public_key_path=${local_public_key_path:-~/.ssh/id_rsa.pub}
-test -f "${local_public_key_path}" || \
-  { echo_err "local user public key not found at $local_public_key_path" && exit 1; }
+[ -f "${local_public_key_path}" ] || \
+  fatal_err "local user public key not found at $local_public_key_path"
 
 # check local user rclone config
 local_rclone_config_path=${local_rclone_config_path:-~/.config/rclone/rclone.conf}
-test -f "${local_rclone_config_path}" || \
-  { echo_err "local user rclone config not found at $local_rclone_config_path" && exit 1; }
+[ -f "${local_rclone_config_path}" ] || \
+  fatal_err "local user rclone config not found at $local_rclone_config_path"
 
 # test connection to remote host via ssh
-ssh -q "$ssh_connection_string" exit
-test $? -eq 0 || { echo_err "Connection to remote via ssh $ssh_connection_string failed" && exit 1; }
-
+if ! (ssh -q "$ssh_connection_string" exit); then
+  fatal_err "Connection to remote via ssh $ssh_connection_string failed"
+fi
 
 # ------------ Backup prerequirements check ------------
 
-if test -n "$backup_name"; then
+if [ -n "$backup_name" ]; then
   # check volumes setting
-  (test -n "$backup_docker_volumes" && test -z "$volumes_rclone_repo") && {
-    echo_err "backup_docker_volumes defined, but volumes_rclone_repo isn't" && exit 1; }
+  [ -n "$backup_docker_volumes" ] && [ -z "$volumes_rclone_repo" ] && \
+    fatal_err "backup_docker_volumes defined, but volumes_rclone_repo isn't"
 
   # check docker mysql settings
-  if test -n "$docker_mysql_db_names"; then
+  if [ -n "$docker_mysql_db_names" ]; then
 
-    test -z "$db_rclone_repo" && {
-      echo_err "docker_mysql_db_names defined, but db_rclone_repo isn't" && exit 1; }
+    [ -z "$db_rclone_repo" ] && {
+      fatal_err "docker_mysql_db_names defined, but db_rclone_repo isn't"; }
 
-    test -z "$docker_mysql_user" && { echo_err "docker_mysql_user not defined" && exit 1; }
+    test -z "$docker_mysql_user" && fatal_err "docker_mysql_user not defined"
 
     # warn on empty password, do not fail
-    test -z "$docker_mysql_password" && { echo_warn "docker_mysql_password not defined"; }
+    [ -z "$docker_mysql_password" ] && { echo_warn "docker_mysql_password not defined (or empty)"; }
   fi
 
   # check host postgresql settings
-  if test -n "$host_postgresql_db_names"; then
+  if [ -n "$host_postgresql_db_names" ]; then
 
-    test -z "$db_rclone_repo" && {
-      echo_err "host_postgresql_db_names defined, but db_rclone_repo isn't" && exit 1; }
+    [ -z "$db_rclone_repo" ] &&  fatal_err "host_postgresql_db_names defined, but db_rclone_repo isn't"
 
-    test -z "$host_postgresql_user" && { echo_err "host_postgresql_user not defined" && exit 1; }
+    [ -z "$host_postgresql_user"] && fatal_err "host_postgresql_user not defined"
     # test -z "$host_postgresql_password" && { echo_err "host_postgresql_password not defined" && exit 1; }
   fi
 
@@ -101,9 +109,9 @@ else
 fi
 
 # If not all telegram settings defined -> ignore but warn, this is optional
-(test -n "$telegram_chat_id" && test -n "$telegram_bot_token") || {
+if ! [ -n "$telegram_chat_id" ] && [ -n "$telegram_bot_token" ]; then
   echo_err "Telegram notifications disabled, please define telegram_chat_id and telegram_bot_token in $config_path";
-}
+fi
 
 echo_ok "Checking complete"
 
@@ -132,6 +140,7 @@ echo $remote_user_password | \
 
 # Run setup on remote host
 ssh "$ssh_connection_string" /bin/bash -e <<- STR
+  umask 077
   # Update distro and setup required toolset
   apt-get update
   apt-get --yes --force-yes upgrade
